server:
  port: 18080
  servlet:
    context-path: /507

spring:
  thymeleaf: #thymelea模板配置
    prefix: classpath:/views/  #模板配置默认 classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8